### ISSUE TITLE
Child entities not upserted

### ISSUE THREAD

**Issue by onionhammer** [artiomchi/FlexLabs.Upsert#77] opened 2019-12-17 18:32 UTC
Looks like child entities are not upserted; I assume this is a known limitation? Are there any plans to add this?

i.e.

```C#
db.Items.Upsert(new Item {
   SubItem = new SubItem {
   }
});
```

**Comment by artiomchi** [comment] 2019-12-25 11:01
Hi @onionhammer 

This is basically a duplicate of #26 

To answer your question - no, this is not supported by this library. You'd have to ensure the child entities (`SubItem`) exist using a separate request, then, use their IDs to populate the FKs in your `Item`s

As mentioned in the linked issue, this library doesn't load the IDs of the upserted entities, so if you were to use Upsert to populate the `SubItem`s, you'd have to run an extra query at this point to get their IDs back

**Closed by artiomchi** 2019-12-25 11:01 UTC
