### ISSUE TITLE
Upsert - when entity is updated, I cannot see changes in context untill I use AsNoTracking()

### ISSUE THREAD

**Issue by PatryxCShark** [artiomchi/FlexLabs.Upsert#106] opened 2021-07-27 09:29 UTC
Hi, 
I noticed a problem when I want to get entity from context after upsert.
Example:

```
var lastReviewAtToUpdate =  DateTime.UtcNow.AddDays(-1);   

var newCar = new Car( { Id = 2, Name = "MY car", LastReviewAt = DateTime.UtcNow });    

var changesCount = _context.Cars.Upsert(newCar)
.WhenMatched(x => new Car
 {
     LastReviewAt = lastReviewAtToUpdate,
 })
 .UpdateIf(x => x.LastReviewAt  <= lastReviewAtToUpdate)
Run();
```

Let's assume that Car with given Id (=2) existed, and UpdateIf is true. I want to get car from context:

`var myCar = _context.Cars.SingleOrDefault(x => x.Id == 2);`

Unfortunately, myCar.LastReviewAt is not refrshed and still the old one!
If I use 
`var myCar = _context.Cars.AsNoTracking().SingleOrDefault(x => x.Id == 2);`
then I have up-to-date LastReviewAt.

I want to have up-to-date entity in context (and not use AsNoTracking() because sometime I will update he entity etc). 
How to do it?

If Upsert add new entity it is automaticaly in context, so such problem does not exist.

I found a workaround but I am not sure if it is required or can be done easily and why it is not automatically updated in context.
My workaround:

```
   if (changesCount > 0)
    {
        // reload because Upsert (update) does not refresh entity in context
        var entity = _context.Cars
            .SingleOrDefault(x => x.Id == 2);
        if (entity != null)
        {
            _context.Entry(entity).Reload(); 
        }
    }
```

@artiomchi Could you comment or give some advices?

**Comment by artiomchi** [comment] 2021-07-28 19:27
This looks to be a duplicate of #59, so a bigger explanation can be found there.

Long story short - it's true that the Upsert library doesn't affect the change tracker.

At the moment, using ReloadAsync() or creating a new context would be my recommended way of handling it, even though it's far from ideal or elegant

**Closed by artiomchi** 2021-07-28 19:27 UTC

**Comment by PatryxCShark** [comment] 2021-07-29 08:13
Thanks!

**Comment by PatryxCShark** [comment] 2021-07-30 09:31
@artiomchi is there any way to have information if entity was added or was updated? Any trick to get such information? It would be better reload given entity just when it was updated (when was added there is no point)?

**Comment by artiomchi** [comment] 2021-07-31 20:51
Unfortunately not - the only way to know that is to load the generated entry back from the database.
