### ISSUE TITLE
Auto-Generable KEY is not included into "AS" and "INSERT" part of query

### ISSUE THREAD

**Issue by MarcorOnline** [artiomchi/FlexLabs.Upsert#38] opened 2019-01-16 17:41 UTC
Hello.
I'm using the version **2.0.4** from Nuget.

My object have a complex key, with two columns:
**OrderNumber** and **OrderChannel**

The second one is not included into **AS** and into **INSERT** query, and an exception will be thrown from SQL.

The reason is that "OrderChannel" have an auto-generated default value.
The problem is this line of code:

```
var properties = entityType.GetProperties()
                .Where(p => p.ValueGenerated == ValueGenerated.Never)
                .ToArray();
```

Here the wrong generated query:

> MERGE INTO [DhlReportData] WITH (HOLDLOCK) AS [T] USING ( VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12) ) 
> 
> AS [S] ([**OrderNumber**], [BillToAccount], [CompanyName], [LicensePlateNo], [OriginStation], [PickupResponse], [Pieces], [PltIndicator], [Product], [ShipmentContents], [ShipmentNumber], [ShipmentResponse], [Weight]) 
> 
> ON **[T].[OrderNumber] = [S].[OrderNumber]** AND **[T].[OrderChannel] = [S].[OrderChannel]** 
> 
> WHEN NOT MATCHED BY TARGET THEN INSERT ([**OrderNumber**], [BillToAccount], [CompanyName], [LicensePlateNo], [OriginStation], [PickupResponse], [Pieces], [PltIndicator], [Product], [ShipmentContents], [ShipmentNumber], [ShipmentResponse], [Weight]) VALUES ([OrderNumber], [BillToAccount], [CompanyName], [LicensePlateNo], [OriginStation], [PickupResponse], [Pieces], [PltIndicator], [Product], [ShipmentContents], [ShipmentNumber], [ShipmentResponse], [Weight]) 
> 
> WHEN MATCHED THEN UPDATE SET [BillToAccount] = [S].[BillToAccount], [CompanyName] = [S].[CompanyName], [LicensePlateNo] = [S].[LicensePlateNo], [OriginStation] = [S].[OriginStation], [PickupResponse] = [S].[PickupResponse], [Pieces] = [S].[Pieces], [PltIndicator] = [S].[PltIndicator], [Product] = [S].[Product], [ShipmentContents] = [S].[ShipmentContents], [ShipmentNumber] = [S].[ShipmentNumber], [ShipmentResponse] = [S].[ShipmentResponse], [Weight] = [S].[Weight];

This is my fix, but I'm not sure that is correct in all scenarios:

```
var properties = entityType.GetProperties()
                .Where(p => p.ValueGenerated == ValueGenerated.Never || p.IsKey())
                .ToArray();
```

**Comment by artiomchi** [comment] 2019-01-24 22:54
Hi, sorry it took a while to respond to this.

This is actually done by design - You shouldn't be using an auto-generated column as the upsert matching key. 

I've explained the reason for this in the wiki:

> The column(s) used can not be database generated, whether it's a database generated Guid, or an auto increment identity key. The reason for that is simple - if the value is auto generated, then you'd never be able to correctly match the values in your passed dataset, and even if you did - you wouldn't be able to insert them with these values, since the database will generate new values on insert.
>
> In the case where you know exactly the values of these generated columns (and they are your unique key), you probably want to run an update operation, not an upsert

**Comment by artiomchi** [comment] 2019-02-21 17:33
I'm closing this issue, since there weren't any updates recently. Let me know if you have any more issues

**Closed by artiomchi** 2019-02-21 17:33 UTC
Labels: question

**Comment by MarcorOnline** [comment] 2019-02-22 09:06
Thanks

I will use a modified version for my environment
