### ISSUE TITLE
No mapping to a relational type can be found for the CLR type 'JObject

### ISSUE THREAD

**Issue by kosnkow** [artiomchi/FlexLabs.Upsert#45] opened 2019-02-19 08:18 UTC
When I try to add JObject value I got 'No mapping to a relational type can be found for the CLR type 'JObject

**Comment by artiomchi** [comment] 2019-02-21 17:29
Umm.. Why would you be trying to insert a `JObject`? I don't think EF Core would even allow you to do that.

You have to pass an instance of one of your table types in your DBContext for the library to work.

Could you provide a sample of your code, so that I can understand what you mean?

**Comment by APIWT** [comment] 2019-02-25 00:07
I would have to agree with @artiomchi
If you want to use EF core in general you need an entity class so I am not sure why you would use a dynamic JSON object.

**Comment by vzwick** [comment] 2019-02-25 00:27
I have a hunch that @kosnkow has a [value conversion](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions) set up for his model class ...

**Comment by Grummle** [comment] 2019-03-10 05:35
I'm running into the same issue @kosnkow. I'm dumping a blog of json into a varchar(max) column and serializing/deserializing it to a JObject.
```csharp
    public class StoreListing 
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string Id { get; set; }
        //some other vanilla properties
        public JObject  OriginalData { get; set; }
    }
```

```csharp
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<StoreListing>()
                .Property(b => b.OriginalData)
                .HasConversion(
                    v => JsonConvert.SerializeObject(v),
                    v => JsonConvert.DeserializeObject<JObject>(v));
        }
```

**Comment by artiomchi** [comment] 2019-03-15 10:10
Hmm.. I did add partial support for conversions, but I guess they don't work everywhere yet.

I'm working on improving the way I'm handling the expression tree for the upsert command, I'll make sure that it properly treats the conversions at every stage. This seems like a bug at the moment

**Comment by artiomchi** [comment] 2021-02-28 14:05
I've taken a look at this and I can't reproduce it in the latest version. I've added some unit tests to run through this case, with a JObject property and the conversions you've used above, and all the unit tests are happy. At this point I'm going to assume that this must have been fixed in a previous release.

If you're still having issues, please let me know again

**Closed by artiomchi** 2021-02-28 14:05 UTC
Labels: bug
