### ISSUE TITLE
ToJson() not saving asjsonb for postgres

### ISSUE THREAD

**Issue by rsr-maersk** [artiomchi/FlexLabs.Upsert#166] opened 2024-09-12 13:36 UTC
Hi @artiomchi, long-time fan of this repo.

But the new owned poco mapping does not appear to be supported

Made PR to prove #165 

Any ideas?

https://www.npgsql.org/efcore/mapping/json.html?tabs=data-annotations%2Cpoco

It is now the recommended way to do jsonb, as ef core can translate to server side json queries

**Comment by artiomchi** [comment] 2024-11-28 22:26
Hey @rsr-maersk - thanks for your kind words as well as your contributions to the repo!

This looks to be a duplicate of #156 which mentioned the same thing, so I'll be closing this ticket, leaving the other one. I don't have a solution for this yet, partially as I don't think I have the time at the moment for getting deep into this :(

**Closed by artiomchi** 2024-11-28 22:26 UTC
