### ISSUE TITLE
Upsert is replacing my previous entity

### ISSUE THREAD

**Issue by forlayo** [artiomchi/FlexLabs.Upsert#37] opened 2019-01-14 09:31 UTC
I've an entity class like this one:
```
public class Device
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string DeviceId { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.None), JsonIgnore]
        public string GroupId { get; set; }

        public string CustomName { get; set; }
        public string Tags { get; set; }
        public string Location { get; set; }

        public string DeviceInfo { get; set; }
        public string LastCmd { get; set; }

        public bool? Online { get; set; }

        public Device() { /* Constructor needed for query */ }

        public Device(string groupId, string deviceId)
        {
            GroupId = groupId;
            DeviceId = deviceId;
        }
    }
```
And then on various method on my applications creating a new device with a parameter changed, like..
```
            var entity = new Device(groupId,/deviceId)
            {
                CustomName = name
            };
```
And inserting it using upsert with the main idea of doing a merge between the new value and the database current one:
```
var db = _contextFactory.GetContext();
await db.Upsert(deviceEntity).RunAsync();
```

But what's happening is the new entity is replacing the previous one on database, instead of changing the field that's new.

What I'm doing wrong?

**Comment by artiomchi** [comment] 2019-01-24 10:19
This is actually the intended behaviour. Upsert is an insert/update operation - if the entity already exists in the database - it will be updated, but it it doesn't - it will be inserted. To insert an entry, you have to have all properties of the entity populated, otherwise only the PK+`CustomName` properties will be updated, everything else will be null.

If your code doesn't worry about doing an insert, because you're sure that the entity already exists in the database, then maybe a regular insert would suit you better.

Alternatively, you might want to specify which columns should be updated in case upsert finds a match.  
By default, it will try to update all columns, and you haven't initialised any of them except `CustomName`.

Something like this would do it:
```csharp
await db.Upsert(deviceEntity).WhenMatched(v => new Device { CustomName = v.CustomName }).RunAsync();
```

You can check the [Usage](https://github.com/artiomchi/FlexLabs.Upsert/wiki/Usage) page for more details

**Comment by artiomchi** [comment] 2019-02-21 17:32
I'm closing this issue, since there weren't any updates recently. Let me know if you have any more issues

**Closed by artiomchi** 2019-02-21 17:32 UTC
Labels: question
